title: Set a background image for the Python turtle screen
hero_image: images/banner.png
description: Set a background image for the Python turtle screen
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Setting a background image
